version: "3.8"
services:
  osmx:
    build:
      context: ./osmx
    image: osmx
    volumes:
      - "./data:/data"
  onramp:
    build:
      context: ./app
    environment:
      - AWS_PROFILE
      - OSMX_DB=/data/pennsylvania.osmx
    image: onramp-app
    volumes:
      - "./app:/app"
      - "./data:/data"
      - $HOME/.aws:/root/.aws:ro
