---

  - name: Install OSMExpress dependencies
    apt:
      state: present
      pkg:
      - cmake
      - clang
      - libbz2-dev
      - libz-dev
      - libexpat-dev
      - libssl-dev

  - name: Checkout OSMExpress repository
    git:
      repo: "https://github.com/protomaps/OSMExpress.git"
      dest: "{{osmexpress_src_dir}}"
      version: "{{osmexpress_version}}"
      force: yes # So that submodule changes in the working copy don't cause error
      recursive: yes
      accept_hostkey: yes

  - name: Configure OSMExpress
    command: cmake -DCMAKE_BUILD_TYPE=Release .
    args:
      chdir: "{{osmexpress_src_dir}}"

  - name: Build OSMExpress
    make:
      chdir: "{{osmexpress_src_dir}}"

  - name: Install OSMExpress
    copy:
      src: "{{osmexpress_src_dir}}/osmx"
      dest: "/usr/local/bin/osmx"
      mode: 0775
      remote_src: yes
