---
  - hosts: all
    become: true

    pre_tasks:
      - name: Update APT cache
        apt: update_cache=yes

      - name: Create data dir on guest
        file:
          path: /data
          state: directory
          mode: '0775'
          owner: vagrant
          group: vagrant

    roles:
      - { role: "onramp.osmexpress" }
